[project]
name = "otc-projector"
version = "0.1.0"
description = "otc-projector"
requires-python = ">=3.14,<3.15"
dependencies = [
    "fastapi",
    "uvicorn",
    "otc-shared-kernel",
    "otc-contracts",
    "otc-cqrs",
]

[build-system]
requires = ["uv_build>=0.12.22,<0.13"]
build-backend = "uv_build"

[tool.uv.sources]
otc-shared-kernel = { workspace = true }
otc-contracts = { workspace = true }
otc-cqrs = { workspace = true }
