"""R1 (domain half), R2: `Money` is int minor units with closed, same-currency arithmetic."""

import dataclasses
import enum
import operator
import typing
from collections.abc import Callable
from decimal import Decimal
from typing import Any

import pytest

from otc_shared_kernel import (
    CurrencyMismatchError,
    DomainError,
    InvalidCurrencyCodeError,
    InvalidMoneyAmountError,
    Money,
    Quantity,
)

INT64_MAX = 9_223_372_036_854_775_807
INT64_MIN = -9_223_372_036_854_775_808


def money(amount: Any, currency: Any = "EUR") -> Money:
    """Construct with arguments the type checker would refuse (runtime refusal is under test)."""
    return Money(amount, currency)


class _Cents(enum.IntEnum):
    ONE = 1


# --------------------------------------------------------------------------- R1 / M1


def test_r1_money_represents_1242_50_eur_as_124250_minor_units_no_decimal_representation() -> None:
    price = Money(124250, "EUR")
    assert price.amount == 124250
    assert type(price.amount) is int
    assert price.currency == "EUR"
    assert str(price) == "124250 EUR"
    assert [f.name for f in dataclasses.fields(Money)] == ["amount", "currency"]
    assert {f.name: f.type for f in dataclasses.fields(Money)} == {"amount": int, "currency": str}


# ALLOWLIST: every name in `vars(Money)` of EVERY kind (public, private, dunder), as a literal. A
# `__format__` or `__repr__` that prints "1242.50 EUR", a private `_major` property, a `RATE`
# attribute, a post-class `Money.__truediv__ = ...` all add a name and fail here, whatever their
# kind or spelling (#8 D1 recurred in this test in its first form: it listed public names and a
# word list of dunders). The dataclass-generated dunders are spelled out; they are the names
# CPython 3.14.8 (`.python-version`) generates for `@dataclass(frozen=True, slots=True)`.
MONEY_MEMBERS = {
    # declared by the class
    "amount",
    "currency",
    "zero",
    "is_negative",
    "is_zero",
    "add",
    "subtract",
    "multiply",
    "compare",
    "_require_same_currency",
    "__post_init__",
    "__add__",
    "__sub__",
    "__mul__",
    "__lt__",
    "__le__",
    "__gt__",
    "__ge__",
    "__str__",
    # generated by @dataclass(frozen=True, slots=True) and the interpreter
    "__eq__",
    "__hash__",
    "__init__",
    "__repr__",
    "__setattr__",
    "__delattr__",
    "__getstate__",
    "__setstate__",
    "__replace__",
    "__match_args__",
    "__slots__",
    "__dataclass_fields__",
    "__dataclass_params__",
    "__annotate_func__",
    "__annotations_cache__",
    "__static_attributes__",
    "__firstlineno__",
    "__module__",
    "__doc__",
}

# Every operator-protocol dunder (derived from the `operator` module, not from a word list) that
# Money is ALLOWED to define. Everything else in `operator` -- __truediv__, __floordiv__, __mod__,
# __pow__, __neg__, __index__, ... -- must be absent.
ALLOWED_OPERATOR_DUNDERS = {
    "__add__",
    "__sub__",
    "__mul__",
    "__lt__",
    "__le__",
    "__gt__",
    "__ge__",
    "__eq__",
    "__ne__",
}
# Conversion and rounding protocols the `operator` module does not list (and the reflected forms).
CONVERSION_DUNDERS = {
    "__float__",
    "__int__",
    "__complex__",
    "__round__",
    "__trunc__",
    "__floor__",
    "__ceil__",
    "__divmod__",
    "__rdivmod__",
    "__rtruediv__",
    "__rfloordiv__",
    "__rmod__",
    "__rpow__",
    "__radd__",
    "__rsub__",
    "__rmul__",
}


def test_r1_money_defines_exactly_the_allowlisted_members_of_every_kind() -> None:
    members = set(vars(Money))
    assert members == MONEY_MEMBERS, (
        f"Money gained or lost a member: +{sorted(members - MONEY_MEMBERS)} "
        f"-{sorted(MONEY_MEMBERS - members)}"
    )


def test_r1_money_offers_no_division_conversion_or_rounding_dunder() -> None:
    operator_dunders = {
        name
        for name, member in vars(operator).items()
        if name.startswith("__") and callable(member)
    }
    assert "__truediv__" in operator_dunders, "the population lost its sentinel"
    forbidden = (operator_dunders - ALLOWED_OPERATOR_DUNDERS) | CONVERSION_DUNDERS
    offered = sorted(name for name in forbidden if name in vars(Money))
    assert offered == [], f"Money defines forbidden numeric protocol members: {offered}"


def test_r1_money_has_no_float_decimal_or_complex_in_any_signature() -> None:
    hints: dict[str, dict[str, Any]] = {}
    for name, member in vars(Money).items():
        target = member.fget if isinstance(member, property) else member
        target = target.__func__ if isinstance(target, classmethod) else target
        if callable(target) and not name.startswith("__post"):
            hints[name] = typing.get_type_hints(target)
    assert {"add", "multiply", "compare"} <= set(hints), "the signature walk reached no methods"
    for name, per_member in hints.items():
        for parameter, hint in per_member.items():
            assert not any(word in str(hint) for word in ("float", "Decimal", "complex")), (
                f"Money.{name} `{parameter}` is typed {hint}: no float/Decimal/complex surface"
            )


@pytest.mark.parametrize(
    "bad",
    [100.0, 100.5, True, False, "100", None, Decimal(100), 1 + 0j, b"1", _Cents.ONE, [1]],
    ids=lambda v: f"{type(v).__name__}-{v!r}",
)
def test_r1_money_refuses_an_amount_that_is_not_a_plain_int(bad: Any) -> None:
    with pytest.raises(InvalidMoneyAmountError) as raised:
        money(bad)
    assert raised.value.code == "money.invalid_amount"


@pytest.mark.parametrize("edge", [INT64_MAX, INT64_MIN, 0, -1])
def test_r1_money_holds_the_whole_int64_range(edge: int) -> None:
    assert Money(edge, "EUR").amount == edge


@pytest.mark.parametrize("beyond", [INT64_MAX + 1, INT64_MIN - 1, 10**30])
def test_r1_money_refuses_an_amount_beyond_the_bigint_column(beyond: int) -> None:
    with pytest.raises(InvalidMoneyAmountError):
        Money(beyond, "EUR")


@pytest.mark.parametrize("code", ["EUR", "GBP", "USD", "JPY", "BHD"])
def test_r1_money_accepts_an_alpha3_capital_currency(code: str) -> None:
    assert Money(1, code).currency == code


@pytest.mark.parametrize(
    "bad",
    ["eur", "EU", "EURO", "", "E1R", " EUR", "EUR\n", "ÉUR", "ＥＵＲ", None, 978],  # noqa: RUF001
    ids=lambda v: f"{type(v).__name__}-{v!r}",
)
def test_r1_money_refuses_a_malformed_currency_code(bad: Any) -> None:
    with pytest.raises(InvalidCurrencyCodeError) as raised:
        money(1, bad)
    assert raised.value.code == "money.invalid_currency_code"


def test_r1_money_is_immutable_hashable_and_slotted() -> None:
    price = Money(5, "EUR")
    with pytest.raises(dataclasses.FrozenInstanceError):
        price.amount = 6  # type: ignore[misc]
    assert not hasattr(price, "__dict__")
    assert hash(Money(5, "EUR")) == hash(price)
    assert {Money(5, "EUR"), Money(5, "GBP")} == {price, Money(5, "GBP")}
    assert len({Money(5, "EUR"), Money(5, "GBP"), Money(6, "EUR")}) == 3


# --------------------------------------------------------------------------- R2 / M2


def test_r2_money_raises_a_domain_error_when_eur_and_gbp_are_added_subtracted_or_compared() -> None:
    eur, gbp = Money(100, "EUR"), Money(40, "GBP")
    for attempt in (
        lambda: eur.add(gbp),
        lambda: eur.subtract(gbp),
        lambda: eur.compare(gbp),
        lambda: eur + gbp,
        lambda: eur - gbp,
    ):
        with pytest.raises(CurrencyMismatchError) as raised:
            attempt()
        assert isinstance(raised.value, DomainError)
        assert raised.value.code == "money.cross_currency"
        assert (raised.value.left_currency, raised.value.right_currency) == ("EUR", "GBP")
    # No implicit conversion happened: both operands are untouched.
    assert (eur, gbp) == (Money(100, "EUR"), Money(40, "GBP"))


@pytest.mark.parametrize(
    "compare",
    [operator.lt, operator.le, operator.gt, operator.ge],
    ids=["lt", "le", "gt", "ge"],
)
def test_r2_each_ordering_operator_raises_across_currencies(
    compare: Callable[[Money, Money], bool],
) -> None:
    with pytest.raises(CurrencyMismatchError):
        compare(Money(1, "EUR"), Money(1, "GBP"))
    # ...and works inside one currency, so the raise is the currency check, not the operator.
    assert compare(Money(1, "EUR"), Money(2, "EUR")) in (True, False)


def test_r2_equality_across_currencies_is_false_not_an_error() -> None:
    # `==` asks "same value?"; ordering asks "which is larger?" and needs a rate (M2). #7 `equals`
    # (money.ts:109) and #8's record-struct equality both answer false.
    assert Money(100, "EUR") != Money(100, "GBP")
    assert not (Money(100, "EUR") == Money(100, "GBP"))  # noqa: SIM201
    assert Money(100, "EUR") == Money(100, "EUR")
    bare: Any = 100
    assert Money(100, "EUR") != bare  # never equal to a bare int


def test_r2_a_mismatch_at_either_operand_position_is_refused() -> None:
    with pytest.raises(CurrencyMismatchError):
        Money(1, "GBP") + Money(1, "EUR")
    with pytest.raises(CurrencyMismatchError):
        Money(1, "GBP") - Money(1, "EUR")


# --------------------------------------------------------------------------- M3 / M4


def test_m3_add_subtract_multiply_are_closed_over_the_same_currency() -> None:
    a, b = Money(1050, "EUR"), Money(250, "EUR")
    assert a.add(b) == Money(1300, "EUR") == a + b
    assert a.subtract(b) == Money(800, "EUR") == a - b
    assert a.multiply(Quantity(3)) == Money(3150, "EUR") == a * Quantity(3)
    assert Money(5, "JPY").multiply(Quantity(2)).currency == "JPY"


def test_m3_there_is_no_division_at_runtime() -> None:
    price: Any = Money(10, "EUR")
    for attempt in (
        lambda: price / 3,
        lambda: price // 3,
        lambda: price % 3,
        lambda: divmod(price, 3),
        lambda: float(price),
        lambda: int(price),
        lambda: round(price),
        lambda: 3 * price,
        lambda: 3 / price,
    ):
        with pytest.raises(TypeError):
            attempt()


@pytest.mark.parametrize("not_a_quantity", [3, True, 2.5, Money(1, "EUR"), "3", None])
def test_m3_multiplication_admits_a_quantity_and_nothing_else(not_a_quantity: Any) -> None:
    # #7 `multiply(quantity: Quantity)` (money.ts:88) and #8 `Multiply(Quantity)` (Money.cs:60)
    # take a Quantity only; a bare int is refused here at runtime too, not only by mypy.
    with pytest.raises(TypeError):
        Money(10, "EUR") * not_a_quantity
    with pytest.raises(AttributeError):
        Money(10, "EUR").multiply(not_a_quantity)


@pytest.mark.parametrize("operation", ["add", "subtract"])
def test_m3_arithmetic_beyond_the_bigint_column_is_refused_not_wrapped(operation: str) -> None:
    edge = Money(INT64_MAX, "EUR") if operation == "add" else Money(INT64_MIN, "EUR")
    with pytest.raises(InvalidMoneyAmountError):
        getattr(edge, operation)(Money(1, "EUR"))
    with pytest.raises(InvalidMoneyAmountError):
        Money(INT64_MAX, "EUR").multiply(Quantity(2))


def test_m4_negative_money_is_representable_and_a_subtraction_may_go_negative() -> None:
    discount = Money(-500, "EUR")
    assert discount.is_negative
    assert not discount.is_zero
    assert Money(100, "EUR").subtract(Money(300, "EUR")) == Money(-200, "EUR")
    assert Money.zero("EUR").is_zero
    assert not Money.zero("EUR").is_negative
    assert Money(-1, "EUR") < Money(0, "EUR") < Money(1, "EUR")


def test_compare_returns_minus_one_zero_one() -> None:
    assert Money(1, "EUR").compare(Money(2, "EUR")) == -1
    assert Money(2, "EUR").compare(Money(2, "EUR")) == 0
    assert Money(3, "EUR").compare(Money(2, "EUR")) == 1


def test_ordering_against_a_non_money_is_a_type_error() -> None:
    with pytest.raises(TypeError):
        Money(1, "EUR") < 5  # noqa: B015
    with pytest.raises(TypeError):
        Money(1, "EUR") + 5


@pytest.mark.parametrize(
    "operation",
    [
        operator.add,
        operator.sub,
        operator.mul,
        operator.lt,
        operator.le,
        operator.gt,
        operator.ge,
    ],
    ids=["add", "sub", "mul", "lt", "le", "gt", "ge"],
)
def test_every_operator_declines_a_foreign_operand_with_a_type_error(
    operation: Callable[[Any, Any], Any],
) -> None:
    for foreign in (5, 2.5, "5", None):
        with pytest.raises(TypeError):
            operation(Money(1, "EUR"), foreign)


def test_r1_every_text_form_of_money_shows_minor_units_never_a_major_unit_decimal() -> None:
    # `__repr__` and `__format__` are names the dataclass already owns, so the member allowlist
    # cannot see a body that prints "1242.50 EUR"; the BEHAVIOUR of every text form is asserted.
    price = Money(124250, "EUR")
    forms = [
        str(price),
        repr(price),
        format(price),
        format(price, ""),
        f"{price}",
        f"{price!r}",
        f"{price!s}",
        "%s" % price,  # noqa: UP031
        "%r" % price,  # noqa: UP031
        "{}".format(price),  # noqa: UP032
    ]
    assert repr(price) == "Money(amount=124250, currency='EUR')"
    assert str(price) == "124250 EUR"
    for text in forms:
        assert "124250" in text, text
        for major in ("1242.5", "1242,5", "1,242"):
            assert major not in text, text
